import DatabaseHandler from './databaseManager.js'

export const initializeDBTable = async () => {
    await DatabaseHandler.multipleQueries([
        ["CREATE TABLE lego_items (unique_id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, image TEXT, price INTEGER, stock INTEGER, slug TEXT, description TEXT, pieces INTEGER, loyalty INTEGER, schema TEXT);", []],
        ["CREATE UNIQUE INDEX idx_lego_items_id ON lego_items (unique_id);", []],
    ]);
    await createDummyData()
};

export const createDummyData = async () => {
    await DatabaseHandler.multipleQueries([
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick 2x3 (Blue)', 'https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/300223.jpg', 5, 100, 'blue-brick-1', 'A blue lego brick for all your lego needs!', 1, 1, 'brick']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick 2x3 (Yellow)', 'https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/300224.jpg', 5, 100, 'yellow-brick-1', 'A yellow lego brick for all your lego needs!', 1, 1, 'brick']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick 2x3 (Green)', 'https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/4220631.jpg', 5, 100, 'green-brick-1', 'A green lego brick for all your lego needs!', 1, 1, 'brick']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick 2x3 (Orange)', 'https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/4153826.jpg', 5, 100, 'orange-brick-1', 'A orange lego brick for all your lego needs!', 1, 1, 'brick']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick 2x3 (Black)', 'https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/300226.jpg', 5, 100, 'black-brick-1', 'A black lego brick for all your lego needs!', 1, 1, 'brick']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick 2x3 (Brown)', 'https://www.lego.com/cdn/product-assets/element.img.lod5photo.192x192/4216668.jpg', 5, 100, 'purple-brick-1', 'A purple lego brick for all your lego needs!', 1, 1,'brick']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Bonsai Tree', 'https://www.lego.com/cdn/cs/set/assets/blt326a7116fcba7be1/10281.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1', 5, 100, 'bonsai-set-1', 'Bonsai trees are a traditional symbol of harmony and balance, so bring a touch of calm to your world with this creative build.', 878, 360, 'set']],
        ["INSERT INTO `lego_items` (name, image, price, stock, slug, description, pieces, loyalty, schema) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);", ['Brick Box', 'https://www.lego.com/cdn/cs/set/assets/blte88e29b40e206dc1/10913.jpg?fit=bounds&format=webply&quality=80&width=320&height=320&dpr=1', 5, 100, 'brick-box-1', 'This fun-filled developmental toy is packed with bricks and pieces that encourage toddlers to explore hands-on creativity and imaginative play. Familiar objects stimulate young minds and colorful shapes invite free-building fun, making this LEGO® DUPLO® starter set the perfect way to inspire any young builder. Educational toy for toddlers! Inside the sturdy storage box, you\'ll find a car with moving wheels, a roof, window, flowers, bread, DUPLO people figures, 1,2,3 numbered bricks… along with an assortment of original bricks in a rainbow of inviting colors. As parents share the joy of combining the bricks and pieces into endless imaginative play possibilities, they experience first-hand their little builder’s precious developmental milestones. Great gifts for preschoolers! DUPLO playsets put open-ended play and self-expression into the hands of budding builders. With colorful, easy-to-hold pieces that excite toddlers\' imaginations, they\'re safe, clean and easy to take wherever you go.', 65, 200, 'kit']]
    ])
};
